apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-service
  name: api-service
spec:
  ports:
  - name: "3333"
    port: 3333
    protocol: TCP
    targetPort: 3333
  selector:
    app: api
  type: ClusterIP
status:
  loadBalancer: {}
