apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api-deployment
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: alpine/socat
        name: api
        command: ["/bin/sh"]
        args: ["-c", "socat - TCP-LISTEN:3333,fork,reuseaddr"]
